"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

sys.path.insert(0, os.path.join(
    os.path.dirname(__file__), '..', '..'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2%8tq3fn^3r$c0i18#jpkkg-@sf)hvc5cxwn04)**3=^(szm18'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost']


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    # 'django.contrib.staticfiles',
    'myapp.apps.MyappConfig',
    'flatpickr',
    'meta_redirect',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mysite.context_processors.site_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
                'NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'


# GLobal settings for all flatpickr inputs
FLATPICKR_SETTINGS = {

    # Name of the theme to use
    # More themes: https://cdn.jsdelivr.net/npm/flatpickr@4.5.2/dist/themes/
    'theme_name': 'airbnb',

    # # Complete URL of theme CSS file
    # # theme_name is ignored if theme_url is provided
    # 'theme_url': 'https://..',

    # # Global HTML attributes for flatpickr <input> element
    # 'attrs': {
    #     'class': 'my-custom-class',
    #     'placeholder': 'Select Date..',
    # },

    # # Global options for flatpickr
    # # More options: https://flatpickr.js.org/options/
    # # Some options are managed by this package e.g mode, dateFormat, altInput
    # 'options': {
    #     'locale': 'bn',             # locale option can be set here only
    #     'dateFormat': 'm/d/Y H:i',  # reflects in altFormat
    # }

    # # HTML template to render the flatpickr input
    # # Instructions: https://github.com/monim67/django-flatpickr/blob/v1.0.0/dev/myapp/templates/myapp/custom-flatpickr-input.html
    # 'template_name': 'myapp/custom-flatpickr-input.html',

    # # Advanced option!!! Use it only if you need to.
    # # Specify CDN roots. Choose where from static JS/CSS are served.
    # # Can be set to localhost (offline setup) or any other preferred CDN.
    # # Examples:
    # #    https://unpkg.com/  # npm_url only
    # #    http://localhost/cdn/
    # #    /static/ or <Empty String>
    # # Defaults:
    # #    npm_url    : https://cdn.jsdelivr.net/npm/
    # #    github_url : https://cdn.jsdelivr.net/gh/

    # 'npm_url': 'https://unpkg.com/',
    # 'github_url': 'http://localhost',
}


# !!! FOR PACKAGE DEVELOPEMENT AND TESTING ONLY!!!
if sys.argv[1].lower() != 'test':
    FLATPICKR_SETTINGS['github_url'] = '/dev/'
